"""Regenerate embedded assets from the user's drivers.json, logos and fonts."""
import json
import unicodedata
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont, ImageOps
root=Path(__file__).resolve().parents[1]
data=json.loads((root/'f1-input/drivers.json').read_text())
ids=[d['car_id'] for d in data['drivers']]
assert len(ids)==len(set(ids)) and all(1<=x<=40 for x in ids)
teams=list(data['teams'])
def cstr(s):
 return json.dumps(unicodedata.normalize('NFKD',s).encode('ascii','ignore').decode())
out=['/* Generated by tools/build_f1_assets.py. */','#ifndef F1ASSETS_H','#define F1ASSETS_H']
defaults=['/* Generated by tools/build_f1_assets.py. */','#ifndef F1DEFAULTS_H','#define F1DEFAULTS_H','#include "f1config.h"']
def arr(lines,name,shape,values):
 lines.append('static const unsigned char '+name+shape+' = {'+','.join(map(str,values))+'};')
# Glyphs: fixed storage, variable advance, common baseline for each font.
for idx,(fn,size) in enumerate([('FORMULA1-DISPLAY-BOLD.TTF',9),('FORMULA1 DISPLAY-REGULAR.TTF',8),('KHINTERFERENCE-REGULAR.OTF',10),('FORMULA1-DISPLAY-BOLD.TTF',12),('FORMULA1 DISPLAY-REGULAR.TTF',4),('FORMULA1-DISPLAY-BOLD.TTF',6)]):
 font=ImageFont.truetype(str(root/'f1-input/fonts'/fn),size)
 pixels=[]; widths=[]
 for c in range(32,127):
  im=Image.new('L',(20,16)); ImageDraw.Draw(im).text((0,0),chr(c),font=font,fill=255)
  pixels.extend(round(p*3/255) for p in im.getdata()); widths.append(min(20,round(font.getlength(chr(c)))))
 arr(out,'f1_font'+str(idx),'[95][320]',pixels); arr(out,'f1_width'+str(idx),'[95]',widths)
defaults.append('static const F1Driver f1_default_drivers[F1_DRIVER_COUNT] = {')
for d in data['drivers']:
 defaults.append('{%d,%d,%d,%s,%s,%s},'%(d['car_id'],d['number'],teams.index(d['team']),cstr(d['abbr']),cstr(d['last']),cstr(d.get('first',''))))
defaults.append('};')
defaults.append('static const char f1_default_team_names[F1_TEAM_COUNT][F1_TEAM_NAME_LEN] = {'+','.join(cstr(data['teams'][t]['name'].upper()) for t in teams)+'};')
colors=[];logos=[]
for key in teams:
 t=data['teams'][key]; colors.extend(bytes.fromhex(t['color'].lstrip('#')))
 im=Image.open(root/'f1-input/logos'/t['logo']).convert('RGBA')
 # Mercedes has thin strokes that disappear at the renderer's alpha cutoff.
 # Crop padding, then preserve their coverage when converting to tiny sprites.
 if key in ('mercedes','astonmartin'):
  bbox=im.getchannel('A').getbbox()
  if bbox: im=im.crop(bbox)
 im=ImageOps.contain(im,(16,12),Image.Resampling.LANCZOS)
 if key in ('mercedes','astonmartin'):
  im.putalpha(im.getchannel('A').point(lambda a: min(255,a*3)))
 canvas=Image.new('RGBA',(16,12)); canvas.alpha_composite(im,((16-im.width)//2,(12-im.height)//2))
 for px in canvas.getdata(): logos.extend(px)
defaults.append('static const unsigned char f1_default_colors[F1_TEAM_COUNT][3] = {'+'{'+ '},{'.join(','.join(map(str,colors[i:i+3])) for i in range(0,len(colors),3)) +'}'+'};')
defaults.append('#endif')
arr(out,'f1_logos','[F1_TEAM_COUNT][192][4]',logos)
out.append('#endif')
(root/'src/f1assets.h').write_text('\n'.join(out)+'\n')
(root/'src/f1defaults.h').write_text('\n'.join(defaults)+'\n')
print('Generated',len(ids),'drivers,',len(teams),'logos, 6 bitmap fonts')
