"""Generate src/f1font90.h: Futura bitmap fonts for the 90s HUD theme.

Each font stores 95 printable ASCII glyphs (32..126) in fixed cells of
CW x CH pixels with 2-bit coverage (0..3), plus a per-glyph advance.
All glyphs share the same top offset, so a common baseline is kept.
"""
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

root = Path(__file__).resolve().parents[1]
FONTS = [
    # name,        file,                        px
    ("TOWER", "FuturaStd-CondensedBold.otf", 11),
    ("SMALL", "FuturaStd-Condensed.otf",      9),
    ("HEAD",  "FuturaStd-CondensedBold.otf", 10),
    ("NAME",  "FuturaStd-CondensedBold.otf", 15),
    ("BIG",   "FuturaStd-CondensedBold.otf", 28),
    ("VALUE", "FuturaStd-CondensedBold.otf", 20),
]

out = ["/* Generated by tools/build_f1_fonts90.py. Futura bitmaps for the 90s theme. */",
       "#ifndef F1FONT90_H", "#define F1FONT90_H",
       "#define F90_FONT_COUNT %d" % len(FONTS)]
table = []
for idx, (name, fn, size) in enumerate(FONTS):
    font = ImageFont.truetype(str(root / "f1-input/fonts" / fn), size)
    asc, desc = font.getmetrics()
    ch = asc + desc
    advances = [max(1, round(font.getlength(chr(c)))) for c in range(32, 127)]
    cw = max(max(advances), max(font.getbbox(chr(c))[2] for c in range(33, 127))) + 1
    pixels = []
    for c in range(32, 127):
        im = Image.new("L", (cw, ch))
        ImageDraw.Draw(im).text((0, 0), chr(c), font=font, fill=255)
        pixels.extend(round(p * 3 / 255) for p in im.get_flattened_data())
    # Cap band of 'H': used to centre text vertically inside boxes.
    hb = Image.new("L", (cw, ch)); ImageDraw.Draw(hb).text((0, 0), "H", font=font, fill=255)
    rows = [y for y in range(ch) if any(hb.getpixel((x, y)) > 127 for x in range(cw))]
    top, base = rows[0], rows[-1]
    out.append("#define F90_%s %d" % (name, idx))
    out.append("static const unsigned char f90_pix%d[%d] = {%s};" % (idx, len(pixels), ",".join(map(str, pixels))))
    out.append("static const unsigned char f90_adv%d[95] = {%s};" % (idx, ",".join(map(str, advances))))
    table.append("{%d,%d,%d,%d,f90_pix%d,f90_adv%d}" % (cw, ch, top, base, idx, idx))
    print(name, "cell %dx%d cap %d..%d" % (cw, ch, top, base))
out.append("typedef struct { int cw, ch, top, base; const unsigned char *pix; const unsigned char *adv; } F90Font;")
out.append("static const F90Font f90_fonts[F90_FONT_COUNT] = {" + ",".join(table) + "};")
out.append("#endif")
(root / "src/f1font90.h").write_text("\n".join(out) + "\n")
print("Generated src/f1font90.h")
