const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const script=fs.readFileSync(path.join(root,'release/EDITOR.html'),'utf8').match(/<script>([\s\S]*?)<\/script>/)[1];
const ctx=vm.createContext({structuredClone,TextEncoder,TextDecoder,Blob,Uint8Array});
vm.runInContext(script.slice(0,script.indexOf("$('export').onclick")),ctx);
const run=s=>vm.runInContext(s,ctx);
const fixture=require('./editor_fixture.cjs').fixture;
const fourteen=fixture(14);
ctx.exe=fourteen.bytes;
run('var roster=readGP2(exe);state=importedState(state,roster);validate(state)');
assert.equal(run('roster.length'),14);
assert.equal(run('state.drivers.length'),28);
assert.equal(run('roster[13].name'),'Pacific');
assert.equal(run('JSON.stringify(roster[13].drivers.map(d=>d.id))'),'[18,21]');
assert.equal(run('state.teams[13].mode'),'color');
run("state.teams[13].mode='custom';state.teams[13].pixels=Array(768).fill(255);state.season='1994';var saved=cfg();var reopened=parseCFG(saved);validate(reopened)");
assert.equal(run('reopened.teams.length'),14);
assert.equal(run('reopened.teams[0].name'),run('state.teams[0].name.toUpperCase()')); 
assert.equal(run('reopened.drivers.length'),28);
assert.equal(run('reopened.teams[13].file'),'SEASONS/LOGOS/1994/TEAM14.F1L');
assert.deepStrictEqual(JSON.parse(run('JSON.stringify(reopened.drivers)')),JSON.parse(run('JSON.stringify(state.drivers)')));
run('var project=JSON.parse(JSON.stringify(state));validate(project)');
assert.equal(run('project.teams[13].pixels.length'),768);
run('project.drivers[27].id=project.drivers[0].id');assert.throws(()=>run('validate(project)'));
const invalid=new Uint8Array(ctx.exe);invalid[fourteen.idsFile+27]=0;ctx.invalid=invalid;
assert.throws(()=>run('readGP2(invalid)'));
ctx.old=fixture(13).bytes;
run('state=importedState(state,readGP2(old));validate(state);validate(parseCFG(cfg()))');
assert.equal(run('state.drivers.length'),26);
console.log('PASS: 14-team EXE, 28 CarIds, CFG/project roundtrips, team-14 logo path, malformed pair rejection, return to 13-team roster.');
