/* Generated by tools/build_f1_assets.py. */
#ifndef F1DEFAULTS_H
#define F1DEFAULTS_H
#include "f1config.h"
static const F1Driver f1_default_drivers[F1_DRIVER_COUNT] = {
{36,3,0,"VER","VERSTAPPEN","Max"},
{11,6,0,"HAD","HADJAR","Isack"},
{28,1,1,"NOR","NORRIS","Lando"},
{13,81,1,"PIA","PIASTRI","Oscar"},
{26,44,2,"HAM","HAMILTON","Lewis"},
{16,16,2,"LEC","LECLERC","Charles"},
{33,63,3,"RUS","RUSSELL","George"},
{12,12,3,"ANT","ANTONELLI","Kimi"},
{14,14,4,"ALO","ALONSO","Fernando"},
{18,18,4,"STR","STROLL","Lance"},
{22,41,5,"LIN","LINDBLAD","Arvid"},
{30,30,5,"LAW","LAWSON","Liam"},
{15,5,6,"BOR","BORTOLETO","Gabriel"},
{27,27,6,"HUL","HULKENBERG","Nico"},
{10,10,7,"GAS","GASLY","Pierre"},
{34,43,7,"COL","COLAPINTO","Franco"},
{23,23,8,"ALB","ALBON","Alex"},
{35,55,8,"SAI","SAINZ","Carlos"},
{31,31,9,"OCO","OCON","Esteban"},
{38,87,9,"BEA","BEARMAN","Oliver"},
{29,17,11,"ARO","ARON","Paul"},
{25,7,11,"DOO","DOOHAN","Jack"},
{19,11,10,"PER","PEREZ","Sergio"},
{21,77,10,"BOT","BOTTAS","Valtteri"},
{20,94,12,"SCH","SCHUMACHER","Mick"},
{24,19,12,"DRU","DRUGOVICH","Felipe"},
};
static const char f1_default_team_names[F1_TEAM_COUNT][F1_TEAM_NAME_LEN] = {"RED BULL","MCLAREN","FERRARI","MERCEDES","ASTON MARTIN","RACING BULLS","AUDI","ALPINE","WILLIAMS","HAAS","CADILLAC","GULF NISSAN","PEUGEOT"};
static const unsigned char f1_default_colors[F1_TEAM_COUNT][3] = {{21,101,192},{255,128,0},{168,0,27},{0,210,190},{0,111,98},{0,51,160},{255,64,0},{7,169,247},{0,67,224},{182,186,189},{120,120,120},{254,145,22},{155,255,128}};
#endif
